version: "3"
   
services:
  database: # any name
    image: postgres:alpine
    container_name: pg_db
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db:/data/postgresql
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - DB_NAME={DB_NAME:-postgres}
      - DB_USER='{DB_USER:-postgres}'
      - DB_PASSWORD={DB_PASSWORD:-password}
    networks:
      - net

  web: # any name
    build: 
      context: backend
      dockerfile: dockerfile
    container_name: backend
    command: >
     sh -c "python manage.py makemigrations &&
            python manage.py waitfordb &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:5000"
    volumes:
      - ./backend:/app/ #get the real-time updates that we makes it to the project into the image
    ports:
      - "5000:5000"
    image: web:django # run the image with django tag
    env_file:
      - ./.env
    depends_on:
      - database
      - redis
    links:
      - database:db
      - redis
    networks:
      - net

  redis: # Remote Dictionary Server.
    image: redis:alpine
    container_name: redis
    volumes:
      - redis:/data/redis
    ports:
      - 6379:6379
    networks:
      - net

  celery:
    container_name: celery
    image: web:django
    restart: always # restart container automatically if it is stopped manually or fails
    command: celery -A drug_store worker -l INFO # get information in terminal
    links:
      - database
      - redis
    volumes:
      - ./backend:/app/
    depends_on:
      - database
      - redis
    env_file:
      - ./.env
    networks:
      - net
    
  celery-beat: 
    container_name: celery_beat
    image: web:django
    restart: always
    command: celery -A drug_store beat -l INFO
    volumes:
      - ./backend:/app/
    env_file:
      - ./.env
    depends_on:
      - celery
    links:
      - database
      - redis
    networks:
      - net

  flower:
    image: mher/flower
    container_name: flower
    command: celery flower --persisten=True 
    # persist our data in flower so that it didn’t go away on every restart of container 
    ports:
      - 5555:5555
    env_file:
      - ./.env
    depends_on:
      - celery
    links:
      - database:db
      - celery
      - celery-beat
    networks:
      - net
   
networks:
  net:

volumes:
  db: 
  redis:
  web: